---
# POD Manifest with Namespace
apiVersion: v1
kind: Pod
metadata: 
 name: vineetapppod
 labels: 
  app: vineetapp
  namespace: vinau356
spec:
  containers:
   - name: vineetcontainer
     image: ashokit/javawebapp
     ports: 
      -containerPort: 8080
---
# Service Manifest with Namespace
apiVersion: v1
kind: Service
metadata:
  name: vineetappsvc
  namespace: vinau356
spec:
  type: NodePort
  selector: 
    app: vineetapp
  ports: 
    - port: 80
      targetPort: 8080
      NodePort: 30003
...

...