# Service Manifest with Namespace
apiVersion: v1
kind: Service
metadata:
  name: vineetappsvc
  namespace: vinau356
spec:
  type: NodePort
  selector: 
    app: vineetapp
  ports: 
    - port: 80
      targetPort: 8080
      NodePort: 30003